### ISSUE TITLE
TSD Depreciated

### ISSUE THREAD

**Issue by adams-zz** [searchkit/searchkit-demo#1]
I cloned the demo to check it out but got it looks like TSD is a core dependency and that has been depreciated for typings.

See: https://github.com/DefinitelyTyped/tsd/issues/269

Cheers!

**Comment by joemcelroy** [comment]
thanks Mike :). Yep we are aware of this. We have switched Searchkit to typings as a trial. We will sort this out for our other projects soon.

Joe

**Comment by blairg23** [comment]
Any luck on fixing this issue? Should we use Typings instead?

**Comment by joemcelroy** [comment]
now using npm to manage the typescript dependencies.
