### ISSUE TITLE
Could you please give more details about how to  start this demo?

### ISSUE THREAD

**Issue by harveyaot** [searchkit/searchkit-demo#11]
when I check out this git project. and  try npm start I got this:

`npm ERR! Linux 3.13.0-100-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! searchkit-demo@1.0.0 start: `node start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the searchkit-demo@1.0.0 start script 'node start.js'.
`
I got npm and nodejs installed.

Thanks team.

**Comment by joemcelroy** [comment]
closing this issue - let me know if you still have an issue. Please use https://github.com/searchkit/searchkit-starter-app unless you strongly want to use typescript.
