### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by bjarman** [searchkit/searchkit-demo#12]
Ok, so apparantly I should have tried http://localhost:3000/demo/demo1 ...doh!
All is good.

Or is it?

I see now that the demo is actually connecting to a remote es, http://demo.searchkit.co/api/movies, what must I do to connect the demo to my local es?

**Comment by joemcelroy** [comment]
You need to change the SearchkitManager url to your local url. See https://github.com/searchkit/searchkit-demo/blob/master/src/demo/demo1.tsx#L29. I recommend you use searchkit-starter-app rather than this repo. This repo is more for our demo site which is live on http://demo.searchkit.co
