### ISSUE TITLE
ERROR in /searchkit-demo/node_modules/@types/react-router/lib/withRouter.d.ts (3,99): error TS2314: Generic type 'PureComponent<P, S>' requires 2 type argument(s).

### ISSUE THREAD

**Issue by svanschalkwyk** [searchkit/searchkit-demo#13]
Hi
"ERROR in /searchkit-demo/node_modules/@types/react-router/lib/withRouter.d.ts (3,99): error TS2314: Generic type 'PureComponent<P, S>' requires 2 type argument(s)."
when running the app.

Node 8.1.2
React 15.6.1
Ubuntu
What else do you need to diagnose? 
Internet says this: https://stackoverflow.com/questions/32506180/error-ts2314-generic-type-componentp-s-requires-2-type-arguments
but I cannot find React.Component in code.

**Comment by joemcelroy** [comment]
thanks, il look into it. If you just want a boilerplate, i strongly advise you not to use this as a base but searchkit-starter-app (https://github.com/searchkit/searchkit-starter-app)

**Comment by TrimA74** [comment]
I am having the same problem...
